#11 general -> executive
afes-website/cappuccino-back pull request #12
Opened 2021-04-12 14:29 UTC by su8ru

close #11

migrate ファイルを変更しています

2021-04-12 14:35 UTC, ibuki2003 requested changes

2021-04-12 14:35 UTC, ibuki2003 commented on app/Resources/UserResource.php
> +                'executive'     => $this->perm_executive == 1,
揃えて

2021-04-12 23:02 UTC, Takeno-hito approved these changes

2021-04-13 03:03 UTC, ibuki2003 approved these changes

2021-04-13 03:15 UTC, merged