Feature/#3 path
afes-website/cappuccino-back pull request #13
Opened 2021-04-18 06:05 UTC by Takeno-hito

まだコントローラーがないですがprを立てて頂きたいとご要望を頂いたので立てます

2021-04-18 06:10 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> +    }
使用可能な文字を限定してるのに `Str::random` はまずいだろ

2021-04-18 06:13 UTC, su8ru commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
なんか… `0` を平然と使うのはよくなくない…？

2021-05-08 10:12 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
使える文字固定するって事?見つけられない事がわかればいいからこれでも良いかなって思ってたんだけど

2021-05-08 10:12 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
使える文字固定するって事?見つけられない事がわかればいいからこれでも良いかなって思ってたんだけど

2021-05-08 11:46 UTC, su8ru commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
まあ ID の新仕様には 0 が含まれるのでいいと思います
形式として間違ってるものでチェックするべきではなくないか？の意でした

2021-05-08 11:50 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
むしろ間違ってるやつ入れておいた方がGuestIdが何になろうと必ず404チェックできるからいいかな、って思ってた

2021-05-09 06:31 UTC, su8ru commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
その意図なら、仕様内・外の 2 種類あるべきだと思います（Outdated）

2021-05-09 06:32 UTC, su8ru commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
じゃあ Resolve していいんじゃないですか

2021-05-09 06:34 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +            "/guests/GB-00000/enter",
test

2021-05-09 09:25 UTC, ibuki2003 requested changes
まだぜんぜん途中 離席するので投げる

2021-05-09 09:25 UTC, ibuki2003 commented on tests/guest/GuestTest.php
> +        $this->actingAs($user)->get("/guests/$guest->id");
```suggestion
        $this->actingAs($user)->get("/guests/{$guest->id}");
```
動くのは分かるけど明示的に括っておきたい

2021-05-09 09:25 UTC, ibuki2003 commented on app/Http/Controllers/ExhibitionController.php
> +            'exh' => $exh_status,
```suggestion
            'exhibition' => $exh_status,
```

2021-05-09 09:25 UTC, ibuki2003 commented on tests/guest/EnterExitTest.php
> +    public function testEnter() {
状態(guest/exhibitionともに)正しく書き変わっていることを確認

2021-05-09 09:25 UTC, ibuki2003 commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
上下それぞれコメントを書いておきたい
できれば共通部分をまとめたい(`foreach (['a','b'] as $guest_id)`とか?)

2021-05-09 09:25 UTC, ibuki2003 commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
この名前を冠すならexitも試すべき(分けたほうがいいと思うけどね)

2021-05-10 00:05 UTC, Takeno-hito commented
> 前言ったのが忘れられてそうなのとレビューがもうすこし後になりそうなので今のうちに言っておく:
いくつかの操作をtransactionで包んでほしいです ログ書き込みに失敗したりとか片方だけ状態が変わって爆死とかあったら嫌なので

2021-05-16 23:57 UTC, ibuki2003 requested changes
testは全部は見てません ほかはひととおり…

2021-05-16 23:57 UTC, ibuki2003 commented on app/Http/Controllers/GuestController.php
> +        if ($reservation_error_code !== null) {
ここでしか使ってないので…
```suggestion
        if (($reservation_error_code = $reservation->getErrorCode()) !== null) {
```

2021-05-16 23:57 UTC, ibuki2003 commented on app/Http/Controllers/GuestController.php
> +            throw new HttpExceptionWithErrorCode(400, 'GUEST_NOT_FOUND');
これは404(testさん…)

2021-06-13 09:34 UTC, su8ru requested changes
PHPDoc の書式

2021-06-13 09:34 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> +/*
```suggestion
/**
```

2021-06-13 09:34 UTC, su8ru commented on tests/guest/GuestTest.php
> +/*
```suggestion
/**
```

2021-06-13 09:34 UTC, su8ru commented on tests/TermTest.php
> +/*
```suggestion
/**
```

2021-06-13 09:34 UTC, su8ru commented on tests/ExhibitionTest.php
> +/*
```suggestion
/**
```

2021-06-13 09:39 UTC, su8ru requested changes
書式、統一したくない？

2021-06-13 09:39 UTC, su8ru commented on tests/ExhibitionTest.php
> + * guest/:get guest/$id:get
```suggestion
 * - /guest/:get
 * - /guest/$id:get
```

2021-06-13 09:39 UTC, su8ru commented on tests/LogTest.php
> + * log/
```suggestion
 * - /log:get
```

2021-06-13 09:39 UTC, su8ru commented on tests/LogTest.php
> +/*
```suggestion
/**
```

2021-06-13 09:39 UTC, su8ru commented on tests/TermTest.php
> + * terms/
```suggestion
 * - /terms:get
```

2021-06-13 09:39 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> + * guests/check-in, guests/$id/check-out:post
```suggestion
 * - /guests/check-in:post
 * - /guests/$id/check-out:post
```

2021-06-13 09:39 UTC, su8ru commented on tests/guest/EnterTest.php
> + * guests/$id/enter:post
```suggestion
 * - /guests/$id/enter:post
```

2021-06-13 09:39 UTC, su8ru commented on tests/guest/ExitTest.php
> + * guests/$id/exit:post
```suggestion
 * - /guests/$id/exit:post
```

2021-06-13 09:39 UTC, su8ru commented on tests/guest/GuestTest.php
> + * guest/:get guest/$id:get
```suggestion
 * - /guest/:get
 * - /guest/$id:get
```

2021-06-13 10:04 UTC, Takeno-hito commented on routes/web.php
> +    $router->get('{id}/check', ['uses' => 'ReservationController@check', 'middleware' => 'auth:reservation,executive']);
これ、そもそもthrottleがスペース無しになってるので統一するならphpcsに登録して欲しい気持ちがあります

```php
$router->post(
    '/auth/login',
    ['uses'=>'AuthController@authenticate','middleware'=>'throttle:5,1']
); // throttled 5 requests/1 min
```

2021-06-13 10:05 UTC, Takeno-hito commented on routes/web.php
> +$router->options('{path:.*}', function () {
別PRです

2021-06-13 10:08 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
んー、これじゃだめです? do while が一番簡潔だと思ったけど (break だと while true 使わないといけないし)

2021-06-13 11:35 UTC, ibuki2003 commented on routes/web.php
> +    $router->get('{id}/check', ['uses' => 'ReservationController@check', 'middleware' => 'auth:reservation,executive']);
ただの文字列リテラルがphpcsでfixできたらそれは大惨事

2021-06-13 12:06 UTC, ibuki2003 commented on database/factories/GuestFactory.php
> +            $valid_character = '234578acdefghijkmnprstuvwxyz';
id_lenが忘れられてて泣いている しないなら理由を教えてください

2021-06-13 12:08 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
> もしくはnotで囲む
コメントは さいごまで よもう！

2021-06-13 12:09 UTC, ibuki2003 commented on tests/guest/GuestTest.php
> +        $this->actingAs($user)->get("/guests/$guest->id");
無言無修正close何
(slackに書いてるならそれはここに書けとなる)

2021-06-13 12:14 UTC, ibuki2003 commented on tests/guest/EnterTest.php
> +        $this->assertEquals($user->exhibition->id, $raw_guest->exhibition_id);
レスポンスを信じちゃだめ
(返信後にtransactionが蹴られてるかもしれないし…)

2021-06-13 12:25 UTC, ibuki2003 commented on tests/guest/GuestTest.php
> +        $this->actingAs($user)->get("/guests/$guest->id");
よく見たら下に差分がある…？ なにこれ？

2021-06-13 12:37 UTC, Takeno-hito commented on tests/guest/GuestTest.php
> +        $this->actingAs($user)->get("/guests/$guest->id");
あ 1行単位でaddしたときに削除行をaddするのを忘れてました(ごめんなさい)

2021-06-13 12:40 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
EnterとExitでファイル分けたのでoutdatedとして閉じてます

2021-06-13 12:41 UTC, Takeno-hito commented on database/factories/GuestFactory.php
> +            $valid_character = '234578acdefghijkmnprstuvwxyz';
忘れられてるだけ

2021-06-13 12:42 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
notで囲む、理解ができなかった コードがほしいです

2021-06-13 12:42 UTC, ibuki2003 commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
共通部分がまるでまとまってない 「できれば」が0として評価される人なら今度から使わないようにしますが…

2021-06-13 12:45 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
ド・モルガンの法則を使ってnotを書かない表現になっているように見えて(書いてる意図もしかして違う？)、「望んでいるものが生成されて*いない*ならば〜」な表現にしたい
スマホコーディングする気力はないからサンプルは欲しければ明日とかになる

2021-06-13 12:49 UTC, Takeno-hito commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
できればを見た上で面倒くさいからそのままにしたくて閉じた、、
EnterTest, ExitTest, で3ファイル目作るとしたらなんて名前のファイルを用意するの？ と結局 Forbidden / ExhNotFound がまとまるくらいだしそれなら別にいっかなという気持ちもあります

2021-06-13 12:51 UTC, ibuki2003 commented on tests/guest/EnterExitTest.php
> +    public function testGuestNotFound() {
enterとexitでなく分散してるように見えてるんだけど
場所指定するついでに新しいconversationにしちゃうね

2021-06-13 12:52 UTC, Takeno-hito commented on routes/web.php
> +    $router->get('{id}/check', ['uses' => 'ReservationController@check', 'middleware' => 'auth:reservation,executive']);
確かに
throttleも一緒になおしてよい？

2021-06-13 12:52 UTC, ibuki2003 commented on tests/guest/EnterTest.php
> +    public function testGuestNotFound() {
これとか assert404からassertEqualsが共通 これを括りたい気持ちがとてもあり…

2021-06-13 12:52 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
明日でよいです

2021-06-13 12:55 UTC, Takeno-hito commented on app/Http/Controllers/ExhibitionController.php
> +        $guest = Exhibition::find($id);
前の仕様の名残です(消し忘れです)

2021-06-13 13:00 UTC, Takeno-hito commented on tests/guest/EnterTest.php
> +    public function testGuestNotFound() {
まぁそうかぁ… Enter Exit 共通のTestファイル作るか、、

2021-06-13 13:01 UTC, ibuki2003 commented on tests/guest/EnterTest.php
> +    public function testGuestNotFound() {
ちがうよ ソースも読めなくなっちゃったの…

2021-06-13 13:03 UTC, Takeno-hito commented on tests/guest/EnterTest.php
> +    public function testGuestNotFound() {
読めなくなっちゃった… 意図を理解した

2021-06-13 15:53 UTC, su8ru requested changes

2021-06-13 15:53 UTC, su8ru commented on tests/ExhibitionTest.php
> +        $this->assertCount($count, get_object_vars($res->exh));
```suggestion
        $this->assertCount($count, get_object_vars($res->exhibition));
```

てかここ複数形じゃないんだね

2021-06-14 13:41 UTC, Takeno-hito commented on routes/web.php
> +    $router->get('{id}/check', ['uses' => 'ReservationController@check', 'middleware' => 'auth:reservation,executive']);
りまいんど

2021-06-14 13:50 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
どうです

2021-06-14 13:57 UTC, ibuki2003 commented on routes/web.php
> +    $router->get('{id}/check', ['uses' => 'ReservationController@check', 'middleware' => 'auth:reservation,executive']);
はい

2021-06-14 14:23 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
```suggest
            } while (!($prefix != 2 || $id != 5));
```
こんな感じ 眠いからどっちもちゃんと読めなくなっちゃったのでもしかしたらコメントで書いておくべきかもしれないね

2021-06-14 14:29 UTC, Takeno-hito commented on app/Http/Controllers/ExhibitionController.php
> +    public function enter(Request $request, $id) {
えー、だめ？

2021-06-14 14:34 UTC, Takeno-hito commented on app/Http/Controllers/ExhibitionController.php
> +            abort(500, 'ExhibitionRoom Not found');
(showLogを消したのでreoslve)

2021-06-14 14:37 UTC, Takeno-hito commented on app/Http/Controllers/GuestController.php
> +        if (!preg_match('/^[A-Z]{2,3}-[2-578ac-kmnpr-z]{5}$/', $request->guest_id)) {
行頭行末 途中に空白改行挟む余地なし だけどこれは singleline ではないの?

2021-06-14 14:40 UTC, ibuki2003 commented on app/Http/Controllers/GuestController.php
> +        if (!preg_match('/^[A-Z]{2,3}-[2-578ac-kmnpr-z]{5}$/', $request->guest_id)) {
regexについての話です `\A\Z`を代わりに使うほうが安全
https://blog.ohgaki.net/ruby-php-regex-issue-difference

2021-06-14 14:47 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
え、こっちの方が読みづらくないです、、?そっちの方が読みやすいというのなら変える

2021-06-14 14:49 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
わかる、書いてて思った(え
コメントで日本語で補足だけしといて

2021-06-14 14:51 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
ところでこれ、 `===` にすべきだったりしますよね、、?

2021-06-14 14:51 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            } while ($prefix == 2 && $id == 5);
するかもね 気付いたのえらい

2021-06-15 03:03 UTC, ibuki2003 requested changes
docのパス先頭にスラッシュないの気持ち悪いです

2021-06-15 06:34 UTC, su8ru requested changes

2021-06-15 06:34 UTC, su8ru commented on tests/ExhibitionTest.php
> +
改行いらない（全テスト）

2021-06-15 06:34 UTC, su8ru commented on tests/ExhibitionTest.php
> +    /**
```suggestion

    /**
```
（全テスト）

2021-06-20 03:29 UTC, su8ru requested changes

2021-06-20 03:29 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> +        $invalid_codes[] = Str::random(self::PREFIX_LENGTH) . '-' . Str::random(self::ID_LENGTH);
Str::random だと許容文字列が生成されてしまうことがあるので、ID_CHARACTER 以外のものは含まれているかチェックする do while が必要

```
1) Tests\guest\CheckInOutTest::testInvalidGuestCode
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'INVALID_WRISTBAND_CODE'
+'WRONG_WRISTBAND_COLOR'

/repo/afes-website/cappuccino-back/tests/guest/CheckInOutTest.php:173
```

2021-06-22 08:43 UTC, su8ru approved these changes

2021-06-22 10:15 UTC, ibuki2003 requested changes
あと少しです!

2021-06-22 10:15 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +            }
```suggestion
            } catch (\Exception $e) {
                var_dump($state);
                throw $e;
            } finally {
                DB::rollBack();
            }
```
動かなかったらごめん…

2021-06-22 10:15 UTC, ibuki2003 commented on app/Http/Controllers/GuestController.php
> +        );
こんな実装はいかが?
```suggestion
        return DB::transaction(function () use ($request, $reservation, $term) {
            $guest = Guest::create(
                [
                    'id' => $request->guest_id,
                    'term_id' => $term->id,
                    'reservation_id' => $request->reservation_id
                ]
            );
            $reservation->update(['guest_id' => $guest->id]);
            return response()->json(new GuestResource($guest));
        });
```

2021-06-23 04:15 UTC, su8ru commented on database/factories/UserFactory.php
> +            'id' => Str::random(16),
unique ついてないの不安にならん？

2021-06-23 04:54 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
>                  DB::rollBack();
…

2021-06-23 05:53 UTC, ibuki2003 approved these changes

2021-06-23 06:22 UTC, su8ru approved these changes

2021-06-23 06:22 UTC, merged