モデル移行
afes-website/cappuccino-back pull request #18
Opened 2021-04-20 08:23 UTC by Takeno-hito

resolve: #17

- build: intervention/image
- feat: migrations
- feat: model
- feat: cappuccino guest_type config
- test: term factory
- test: ActivityLog factory
- test: exhibition factory
- test: guest factory
- test: reservation factory
- fix: apply cappuccino config
- test: generate correctly guestId when factory create
- test: fix activityLog factory
- fix: remove guest_id column
- chore: edit order of migration
- refactor: separate setting foreign file into each table migration
- fix: exhibition model
- test: fill exhibition name as same as user name
- test: rename attribute name "exh_id" to "exhibition_id"
- test: set Term Id unique
- test: set relation to guest
- feat: resources
- feat: user and exhibition relation
- fix: use models count function
- fix: relation between user and exhibition
- style: fix over indent
- refactor: rename to ExhibitionResource
- fix: dont count already exited guest

2021-04-20 09:21 UTC, ibuki2003 requested changes
- timestampはデフォ値をあげないとupdateで簡単に壊れるので設定しましょう
  - termsのはdatetimeでもいいかもしれない(useCurrentはおかしい)
  - 参考: [俺のtimestampがこんな挙動なわけがない - Qiita](https://qiita.com/usk81/items/4b8d5a691e4f578d13c9)
- foreign constraintがいくつか足りない
  - exhibition -> image
  - reservation -> term

2021-04-20 09:21 UTC, ibuki2003 commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
…guest_idって、誰のこと?

2021-04-20 09:21 UTC, ibuki2003 commented on app/Models/Reservation.php
> +    public function getErrorCode() {
こういうのこそphpdocを書いてないときnullであることを書いておくといいのでは

2021-04-20 09:21 UTC, ibuki2003 commented on app/Models/User.php
> +        return $this->hasOne('\App\Models\Exhibition', 'id');
```suggestion
        return $this->belongsTo('\App\Models\Exhibition', 'id');
```

2021-04-20 09:35 UTC, Takeno-hito commented on app/Models/Exhibition.php
> +                ->where('exited_at', '!=', null)
(実はこれ、そもそも==nullのものをピックアップしないといけなくて私が実装を間違えてます)

2021-04-20 09:37 UTC, Takeno-hito commented on database/factories/GuestFactory.php
> +    public function createGuestId(string $guest_type): string {
テストでのguestId生成に使うつもりだった(logInとか)

2021-04-20 09:37 UTC, Takeno-hito commented on database/factories/ReservationFactory.php
> +            'people_count'=>$this->faker->numberBetween(1),
100とか現実的な値を上限に設定しておいてもいい？

2021-04-20 09:39 UTC, Takeno-hito commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
チェックイン済みかどうかと接触追跡のために保管せざるを得ないです それともチェックイン済みかどうかのフラグを別に用意するべき？

2021-04-20 09:40 UTC, ibuki2003 commented on database/factories/ReservationFactory.php
> +            'people_count'=>$this->faker->numberBetween(1),
いいとおもう

2021-04-20 09:40 UTC, ibuki2003 commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
DB定義にないので

2021-04-20 09:42 UTC, Takeno-hito commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
え、それまじ？そういやCheckinとかの移行はまだだったな

2021-04-20 09:43 UTC, ibuki2003 commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
そしてguest複数みたいな話があったと思うので`guests()->exists()`するかフラグ用意するかかな 後者推しです

2021-04-20 13:05 UTC, Takeno-hito commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
複数人予約系統はまだ予約の流れを確定させてないから後回しにしておきたい気持ちがあります

2021-04-20 13:06 UTC, Takeno-hito commented on app/Models/Reservation.php
> +    public function getErrorCode() {
というと(あまりよくわかってないです

2021-04-20 13:07 UTC, ibuki2003 commented on app/Models/Reservation.php
> +        if ($this->guest_id !== null) {
それがあっても対応できるように予約にゲストidをもたせるなって話なんですが…

2021-04-20 14:44 UTC, Takeno-hito commented on app/Models/User.php
> +        return $this->hasOne('\App\Models\Exhibition', 'id');
UserがExhibitionを持ってる感じがすると思ってそうしたんだけどダメですか

2021-04-20 15:25 UTC, ibuki2003 commented on app/Models/User.php
> +        return $this->hasOne('\App\Models\Exhibition', 'id');
雰囲気のためならパフォーマンスさえ捨てるんですか？

2021-04-20 15:31 UTC, ibuki2003 commented on app/Models/Reservation.php
> +     * @return string|null ErrorCode (If there are problem to check-in)
theにつられて直すと思ってた 言わなかったのはごめんなさい
単複混ざってるのをどうにかしてください…
(どちらかというとないときにnullということを重点的に説明したかったりします)

2021-04-20 23:40 UTC, Takeno-hito commented on app/Models/User.php
> +        return $this->hasOne('\App\Models\Exhibition', 'id');
え、パフォ変わる？

2021-04-21 02:58 UTC, ibuki2003 commented on app/Models/User.php
> +        return $this->hasOne('\App\Models\Exhibition', 'id');
たしかにこのテーブル構造だと発行されるクエリ同じなのか 気持ち悪いな
ならまあこのままでもいいかも

2021-04-21 12:00 UTC, ibuki2003 requested changes
- exhibition -> user のforeignもあるべき?
- リレーションのメソッドへの引数、今文字列で渡しているのを`ClassName::class`にしたい 存在チェックが効いてうれしいので

2021-04-22 06:49 UTC, Takeno-hito commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1hour'),
期間外のものを使うの期間外チェックテスト以外じゃ稀かなと思いまして
stateを使って期間外を実装する方法はある (UserFactoryのpermissionを参照していただけると)

2021-04-22 06:50 UTC, Takeno-hito commented on app/Resources/ActivityLogResource.php
> +            'log_type' => $this->log_type
別prでいい?

2021-04-22 06:50 UTC, Takeno-hito commented
exhibition->userのforeignは既にあると思います

2021-04-22 06:50 UTC, ibuki2003 commented on app/Resources/ActivityLogResource.php
> +            'log_type' => $this->log_type
#19

2021-04-22 06:51 UTC, Takeno-hito commented on app/Resources/ActivityLogResource.php
> +            'log_type' => $this->log_type
はい。

2021-04-22 06:55 UTC, ibuki2003 commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1hour'),
テストのときは常に期間を明示的に指定するべきで、ここでのランダムにその縛りがあるのは違うという話 明示指定を強制するために行消すのもあり

2021-04-22 07:06 UTC, Takeno-hito commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1hour'),
```php
public function definition() {
        return [
            'id' => $this->faker->unique()->realText(16),
            'enter_scheduled_time' => $this->faker->dateTime,
            'exit_scheduled_time' => $this->faker->dateTime,
            'guest_type' => array_rand(config('cappuccino.guest_types'))
        ];
    }

    public function valid() {
        return $this->state([
            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1sec'),
            'exit_scheduled_time' => $this->faker->dateTimeBetween('+1sec', '+1year'),
        ]);
    }

    public function expired() {
        return $this->state([
            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1sec'),
            'exit_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1sec'),
        ]);
    }

    public function notValid() {
        return $this->state([
            'enter_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1sec'),
            'exit_scheduled_time' => $this->faker->dateTimeBetween('-1year', '-1sec'),
        ]);
    }
```

とかはどうですか(明示的に指定できる)

2021-04-22 09:30 UTC, ibuki2003 requested changes
timestampのデフォ値がまだあんまりないのでそこも追加してください useCurrentとかは指定したうちに入らないと思ってもらって…

2021-04-22 09:30 UTC, ibuki2003 commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $enter,
このへん、明示的に与えさせたいのでこっちの指定を消したい(slackで話したとおり)

2021-04-22 12:39 UTC, Takeno-hito commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $enter,
Term情報の新旧に全く興味を持たないテストもあるので流石にdefaultは欲しい気がします

2021-04-22 12:54 UTC, ibuki2003 commented on database/factories/TermFactory.php
> +            'enter_scheduled_time' => $enter,
その視点はなかったな…ならいいか

2021-04-23 06:32 UTC, Takeno-hito commented
Timestampのデフォ値って具体的に何を指してますか useCurrentはCurrentであるべきものが入ってるはずでそうなってないものはnullableになってます

2021-04-23 13:14 UTC, ibuki2003 approved these changes

2021-04-23 15:46 UTC, su8ru requested changes

2021-04-23 15:46 UTC, su8ru commented on app/Resources/ActivityLogResource.php
> +            'timestamp' => $this->timestamp->toIso8601ZuluString(),
わざわざ `toIso8601ZuluString()` なんてするよりも `toIso8601String()` でよくないですか
 そんな UTC にする理由ある？

2021-04-24 06:52 UTC, su8ru requested changes

2021-04-24 06:52 UTC, su8ru commented on config/app.php
> +    'timezone' => env('APP_TIMEZONE', 'Asia/Tokyo'),
.env.example も Asia/Tokyo に更新したくない?

2021-04-24 13:46 UTC, ibuki2003 approved these changes

2021-04-24 14:05 UTC, su8ru requested changes

2021-04-24 14:05 UTC, su8ru commented on database/migrations/2021_04_11_172418_create_terms_table.php
> +            $table->dateTimeTz('exit_scheduled_time');
timestamp に統一しましょう（バグの温床になると嫌なので）

```suggestion
            $table->timestamp('enter_scheduled_time')->default('2000-01-01 00:00:00');
            $table->timestamp('exit_scheduled_time')->default('2000-01-01 00:00:00');
```

2021-04-26 02:56 UTC, su8ru approved these changes

2021-04-26 05:34 UTC, ibuki2003 approved these changes

2021-04-26 05:34 UTC, merged