#29 複数人の CheckIn に対応
afes-website/cappuccino-back pull request #30
Opened 2021-06-28 07:32 UTC by Takeno-hito

一行で変更済んじゃった
resolve: #29
- feat: to allow multiple people check in
- test: CheckInMultiple
- test: update testAlreadyEnteredReservation to check when all member already checked in

2021-06-28 08:51 UTC, ibuki2003 requested changes

2021-06-28 08:51 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +        }
already_enteredを返すことをテストするところが存在しないのでこの後ろにでも

2021-06-28 12:04 UTC, Takeno-hito commented on tests/guest/CheckInOutTest.php
> +        }
分かりづらくて申し訳ないけど113行目付近がそれに該当します

2021-06-28 12:08 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +        }
ほんとだ 見逃してたごめん
じゃあ91行目のコメントを直しておいてください

2021-06-28 15:21 UTC, su8ru commented on app/Models/Reservation.php
>              return 'ALREADY_ENTERED_RESERVATION';
afes-website/docs#258 待ち

2021-06-29 02:28 UTC, su8ru requested changes
afes-website/docs#258 関連

2021-06-29 02:28 UTC, su8ru commented on app/Models/Reservation.php
>              return 'ALREADY_ENTERED_RESERVATION';
```suggestion
            return 'ALL_MEMBER_CHECKED_IN';
```

2021-06-29 03:42 UTC, su8ru requested changes
`member_checked_in` についてのテストが存在しない？

2021-06-29 03:42 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> +            } while (Guest::find($new_guest_id));
`createGuestId` の中で do while したほうがよくないか

2021-06-29 07:38 UTC, su8ru approved these changes

2021-06-29 08:20 UTC, ibuki2003 approved these changes

2021-06-29 21:54 UTC, merged