#21 Image の実装
afes-website/cappuccino-back pull request #32
Opened 2021-07-14 15:46 UTC by Takeno-hito

りーだぶるこーどの test の部分だけ読んで出来上がった pr です
resolve: #21

2021-07-15 03:28 UTC, ibuki2003 requested changes

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +        $mine_type = $file->getMimeType();
~あなたのタイプには興味ないです~

```suggestion
        $mime_type = $file->getMimeType();
```
(後のもよしなに変えてね…)

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +        if (!$request->hasFile('content'))abort(400, 'file is not uploaded');
phpcsで治らなかったなら設定ミスごめんなさいなんだけど、スペース有無が統一されてなくてもやっとします
```suggestion
        if (!$request->hasFile('content')) abort(400, 'file is not uploaded');
```

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +        if (!$request->hasFile('content'))abort(400, 'file is not uploaded');
phpcsで治らなかったなら設定ミスごめんなさいなんだけど、スペース有無が統一されてなくてもやっとします
```suggestion
        if (!$request->hasFile('content')) abort(400, 'file is not uploaded');
```

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +            });
```suggestion
            $content_medium->widen(1440, function ($constraint) { $constraint->upsize(); });
```
こうスッキリさせちゃってもいいかも 怒られるかな

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +        $content_medium = \Intervention\Image\Facades\Image::make($file->get());
ここから下の処理をImageクラスの仕事にしたい

2021-07-15 03:28 UTC, ibuki2003 commented on database/migrations/2021_07_02_222328_add_small_image_content_column.php
> +            $table->binary('content_small');
blobは64kiBまでです 参考として1440x1440のノイズ 8bit pngが6MB
https://github.com/afes-website/back/blob/develop/database/migrations/2020_03_11_021218_expand_images_blob.php

2021-07-15 03:28 UTC, ibuki2003 commented on tests/ImageTest.php
> +class ImageTest extends TestCase {
404のテストはなくていいの

2021-07-15 03:28 UTC, ibuki2003 commented on database/migrations/2021_07_02_222328_add_small_image_content_column.php
> +            $table->binary('content_small');
これsmallじゃない方は拡張されてますっけ 不安になってきた

2021-07-15 03:28 UTC, ibuki2003 commented on database/factories/ImageFactory.php
> +            ),'user_id' => User::factory(),
```suggestion
            ),
            'user_id' => User::factory(),
```

2021-07-15 03:28 UTC, ibuki2003 commented on app/Http/Controllers/ImageController.php
> +        $flag = $request->query('flag');
ナマエ チガウ
```suggestion
        $flag = $request->query('size');
```

2021-07-15 14:29 UTC, Takeno-hito commented on app/Http/Controllers/ImageController.php
> +        if (!$request->hasFile('content'))abort(400, 'file is not uploaded');
phpcsでなおらないです

2021-07-15 14:33 UTC, Takeno-hito commented on app/Http/Controllers/ImageController.php
> +            });
![image](https://user-images.githubusercontent.com/18237819/125805951-108d1d23-5f35-4d51-82e1-d3b0aae573de.png)
とのことですがどうしますか

2021-07-15 14:37 UTC, Takeno-hito commented on database/migrations/2021_07_02_222328_add_small_image_content_column.php
> +            $table->binary('content_small');
されてました

2021-07-17 08:59 UTC, Takeno-hito commented on app/Http/Controllers/ImageController.php
> +        $content_medium = \Intervention\Image\Facades\Image::make($file->get());
Imageclass内でこの辺りを処理する方法がわかんないです ってかそういう処理をcontrollerがするものではないの

2021-07-17 09:37 UTC, su8ru requested changes

2021-07-17 09:37 UTC, su8ru commented on tests/ImageTest.php
> +     * LoginしてないときはUploadができない
スペースの有無、見てて気にならないんですか？

```suggestion
     * Login してないときは Upload ができない
```

2021-07-17 09:37 UTC, su8ru commented on tests/ImageTest.php
> +    public function testDownload($upload, $medium, $small) {
download……？download かぁ……という気持ちに

upload の対義語としては妥当性があるけど、なんかニュアンスとして……

2021-07-17 09:45 UTC, su8ru requested changes

2021-07-17 09:45 UTC, su8ru commented on tests/ImageTest.php
> +    public function testUpload($upload) {
post

2021-07-17 09:45 UTC, su8ru commented on tests/ImageTest.php
> +    public function testDownload($upload, $medium, $small) {
get

2021-07-17 09:49 UTC, su8ru requested changes

2021-07-17 09:49 UTC, su8ru commented on app/Http/Controllers/ImageController.php
> +
？

2021-07-17 09:54 UTC, su8ru requested changes

2021-07-17 09:54 UTC, su8ru commented on app/Http/Controllers/ImageController.php
> +        if (!$request->hasFile('content')) abort(400, 'file is not uploaded');
```suggestion
        if (!$request->hasFile('content')) abort(400, 'file is not attached');
```

attached とかのほうがよくないですか？このエラー出たとき意味がわからなかった

2021-07-17 09:54 UTC, su8ru commented on app/Http/Controllers/ImageController.php
> +        if (substr($mime_type, 0, 6) !== 'image/') abort(400, 'uploaded file is not an image');
```suggestion
        if (substr($mime_type, 0, 6) !== 'image/') abort(400, 'attached file is not an image');
```

こっちも同様に attached のほうがいい気がします
upload 操作が完了していないゆえ uploaded file ではないと思うので

2021-07-17 10:04 UTC, su8ru approved these changes

2021-07-17 10:21 UTC, ibuki2003 requested changes
これだけ おねがいします

2021-07-17 10:21 UTC, ibuki2003 commented on app/Models/Image.php
> +        return Image::create([
```suggestion
        return self::create([
```

2021-07-17 12:24 UTC, ibuki2003 approved these changes

2021-07-17 12:28 UTC, su8ru approved these changes

2021-07-17 12:28 UTC, merged