#31 GuestIdフォーマットの変更
afes-website/cappuccino-back pull request #33
Opened 2021-07-17 14:05 UTC by Takeno-hito

予約の方は post しないので特に変更することもなかったです。
resolve: #31
- chore: update valid character and format
- feat: check digits
- test: can use prefix in createGuestId()
- test: update create Guest Id
- test: refactor testWrongWristbandColor
- test: testCheckSumFail

2021-07-17 14:24 UTC, ibuki2003 requested changes

2021-07-17 14:24 UTC, ibuki2003 commented on app/Http/Controllers/GuestController.php
> +        $digits = [];
Guestモデル側で見たくない? `static function validate()->bool` または createのoverride

2021-07-17 14:24 UTC, ibuki2003 commented on database/factories/GuestFactory.php
> +                $digits_sum += hexdec($d) * (1 + ($i % 2) * 2);
怪しいことをしない(マジックナンバーと同様)
Guestモデルに入れたほうがいいよやっぱり

2021-07-17 14:24 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +        if ($prefix) $guest_id = $prefix."-".substr($guest_id, 3);
```suggestion
        if ($prefix) $guest_id = $prefix . "-" . substr($guest_id, 3);
```

2021-07-17 14:24 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +        if ($prefix) $guest_id = $prefix."-".substr($guest_id, 3);
ここで調べると`do{}while`した意味ないと思うんですけど、、、

factory::createGuestIdにprefix渡せるようにしたほうが綺麗じゃないですか?

2021-07-17 14:24 UTC, ibuki2003 commented on tests/guest/CheckInOutTest.php
> +        $guest_id = substr($guest_id, -1). ($guest_id[-1] === '0' ? '1' : '0');
```suggestion
        $guest_id = substr($guest_id, -1) . ($guest_id[-1] === '0' ? '1' : '0');
```

2021-07-17 14:34 UTC, su8ru requested changes

2021-07-17 14:34 UTC, su8ru commented on tests/guest/CheckInOutTest.php
> +    private static function createGuestId(string $guest_type, $prefix = null): string {
`$prefix` の型

2021-07-17 14:34 UTC, su8ru commented on app/Models/Guest.php
> +    const VALID_FORMAT = '/\A[A-Z]{2}-[0-9a-f]{5}\Z/';
> 内部データは upper で管理、ただし入力はどちらでも受け取れるように
afes-website/docs#259

id 受け取った直後に upper 処理しちゃえば、仮に prefix が小文字で来てもおっけーになってはっぴー

reservation にも同様の変更をおねがいします

2021-07-18 01:08 UTC, Takeno-hito commented on database/factories/GuestFactory.php
> +                $digits_sum += hexdec($d) * (1 + ($i % 2) * 2);
ランダムID生成は流石にfactoryの仕事じゃない？

2021-07-18 03:54 UTC, su8ru requested changes

2021-07-18 03:54 UTC, su8ru commented on app/Models/Guest.php
> +    const VALID_CHARACTER = '0123456789ABCDEF';
ここに abcdef も入れて小文字も混ざるようにしたい

(16/22)^5 = 0.20... なので、20% の確率で数字と大文字から構成されて見落とす可能性があるけど、まあいいんじゃない？

2021-07-18 07:36 UTC, ibuki2003 commented on database/factories/GuestFactory.php
> +                $digits_sum += hexdec($d) * (1 + ($i % 2) * 2);
ランダム生成について触れてるつもり一切ないんですが チェックサム算出よ

2021-07-18 12:59 UTC, Takeno-hito commented on database/factories/GuestFactory.php
> +                $digits_sum += hexdec($d) * (1 + ($i % 2) * 2);
チェックサム算出をmodelがやるの?あんまり意図を理解できてないです

2021-07-18 13:02 UTC, ibuki2003 commented on database/factories/GuestFactory.php
> +                $digits_sum += hexdec($d) * (1 + ($i % 2) * 2);
> チェックサム算出をmodelがやるの?
はい

digits_sumの計算ロジックがいろんなところに分散するの嫌じゃないんですか? 仕様として決めたならモデルに役割分担して任せるのが安全安心という話

2021-07-18 13:42 UTC, ibuki2003 requested changes
phpcsルールが弱くてごめんなさいね

2021-07-18 13:42 UTC, ibuki2003 commented on database/factories/GuestFactory.php
> +            $guest_id = $prefix . "-" . $id.Guest::calculateParity($id);
あのですね
```suggestion
            $guest_id = $prefix . "-" . $id . Guest::calculateParity($id);
```

2021-07-18 13:45 UTC, ibuki2003 approved these changes
おつかれ

2021-07-18 14:28 UTC, su8ru approved these changes
おつ〜　長かったね

2021-07-18 14:46 UTC, merged