#34 テストの改善
afes-website/cappuccino-back pull request #35
Opened 2021-07-18 01:53 UTC by Takeno-hito

resolve: #34 
## 改善項目
- [x] expectErrorResponse を使って重複した行を大量に削った
- [x] testMultipleError 内のケースを dataProvider を利用して分割
- [ ] テスト内で特段の理由がない限り複数回テストをしないようにする
  - すでにデータがあった状態でデータを作っても問題が発生してないかも試したいからよく考えた方がいいのかも？ 
- [ ] テストケースを作るかも？ [memo: testwith](https://phpunit.readthedocs.io/ja/latest/annotations.html#testwith)

2021-09-13 16:14 UTC, ibuki2003 reviewed
めも: #50 とかの対応を忘れない(mergeするだけか)

2021-09-13 16:14 UTC, ibuki2003 commented on tests/TestCase.php
> +        $this->assertResponseStatus(400);
引数に指定できるようにしたいね

2021-10-02 06:55 UTC, su8ru submitted a review, later dismissed

2021-10-02 06:56 UTC, ibuki2003 requested changes
ちょいちょい漏れてる やりなおし

2021-10-02 07:00 UTC, ibuki2003 approved these changes

2021-10-02 07:01 UTC, su8ru approved these changes

2021-10-02 07:02 UTC, merged