#43 ユーザー管理・セッション鍵実装
afes-website/cappuccino-back pull request #44
Opened 2021-08-30 15:49 UTC by su8ru

close #43

あとはてすと

2021-08-31 17:38 UTC, ibuki2003 requested changes
ねむい

2021-08-31 17:38 UTC, ibuki2003 commented on tests/AuthJwtTest.php
> +        $admin_user=User::factory()->create([
すぺーす…？

2021-08-31 17:38 UTC, ibuki2003 commented on tests/AuthJwtTest.php
> +            'permissions' => [
permはデフォ全0な気がします

2021-08-31 17:38 UTC, ibuki2003 commented on tests/AuthJwtTest.php
> +        $protectedProperty = new \ReflectionProperty($this->app['auth'], 'guards');
何かしらコメントはあったほうがいいかと思われ

2021-09-01 00:07 UTC, su8ru commented on tests/AuthJwtTest.php
> +            'permissions' => [
デフォ値をテストにハードコードしてうれしいことある？

2021-09-01 00:35 UTC, ibuki2003 commented on tests/AuthJwtTest.php
> +            'permissions' => [
たしかに… なんかコード見てランダムなのを検証してるように読めてしまって違和感があったので

2021-09-01 00:41 UTC, ibuki2003 approved these changes

2021-09-01 01:13 UTC, merged