#49 rsv check の 404 で error_code が返ってきていなかった問題を修正
afes-website/cappuccino-back pull request #50
Opened 2021-09-11 06:42 UTC by su8ru

fix #49

2021-09-11 11:41 UTC, Takeno-hito requested changes
testがほしいです(作ってなくてごめんなさい…)

2021-09-11 11:46 UTC, Takeno-hito commented on app/Http/Controllers/ExhibitionController.php
> +            throw new HttpExceptionWithErrorCode(404, 'EXHIBITION_NOT_FOUND');
ん、docs によると結局 show に関しては404の時に特にエラーコードとかはつけてなかったんですけどつけないとだめ？

2021-09-11 11:47 UTC, Takeno-hito commented on app/Http/Controllers/ExhibitionController.php
> +            throw new HttpExceptionWithErrorCode(404, 'EXHIBITION_NOT_FOUND');
で、もし付けるんだったらテストを変えてほしいです

2021-09-13 15:27 UTC, Takeno-hito approved these changes

2021-09-13 16:17 UTC, ibuki2003 requested changes
slackに投げちゃったけど: error_codeはabortの第二引数が使えるはずです→#51

2021-09-13 16:30 UTC, ibuki2003 approved these changes

2021-09-13 16:30 UTC, su8ru reviewed
Approve

2021-09-13 16:30 UTC, Takeno-hito commented
> slackに投げちゃったけど: error_codeはabortの第二引数が使えるはずです

こいつは #51 でまとめて対応

2021-09-13 16:31 UTC, merged